spring.application.name=employee

spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=Dhyey@2005

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=user
spring.security.user.password=123456

logging.level.com.ems.employee=INFO

jwt.secret=Pz7B0ODGseuQn8YcWvV32kqgRm1KuD0eQt6zblPh9Zs=